update for Centos7

diff --git a/tests/test-template.in b/tests/test-template.in
--- a/tests/test-template.in
+++ b/tests/test-template.in
@@ -6,18 +6,17 @@ if test -d ../fw/bin
     export PATH
   fi
 
-if test -z "$MAKE"
-  then
-    gmake=`which gmake`
-
-    if test $? = 0 
-      then
-        MAKE=gmake
-      else
-        MAKE=make
-      fi
-  fi
-
+# fix for newer automake which doesn't seem to work well when called
+# recursively.
+# what was happening is that the TEST_LOGS at the top level were sent
+# to sub-levels and caused errors like
+#
+# fatal: making test-suite.log: failed to create test-canonicalize-package.trs
+# fatal: making test-suite.log: failed to create test-canonicalize-package.log
+#
+# so this fixes that by zeroing out the TEST_LOGS
+MAKEFLAGS=`echo "$MAKEFLAGS" | perl -pe 's/TEST_LOGS=([^=]*)/TEST_LOGS=/'`
+export MAKEFLAGS
 (
 set -x
 rm -rf cvstmp
@@ -64,12 +63,12 @@ perl -pi -e 's/^.*fw-template-erlang.*$//g' fw/template/erlang/load-config
 ( cvs -n -q up | grep '^?' ) && exit 1
 diff -q ../../tmp.app src/tmp.app || exit 1
 touch src/.dialyzer_ok
-"${MAKE}" -s check || exit 1
+"@GMAKE@" -s check || exit 1
 ( cvs -n -q up | grep '^?' ) && exit 1
 
 if test "@FW_NATIVE_PACKAGE_TYPE@" != none
   then
-    "${MAKE}" "package-@FW_NATIVE_PACKAGE_TYPE@" || exit 1
+    "@GMAKE@" "package-@FW_NATIVE_PACKAGE_TYPE@" || exit 1
     ( cvs -n -q up | grep '^?' | grep -v fw.local ) && exit 1
     fw-exec template/erlang/release-ok || exit 1
     echo "dild" > src/tmp.app
@@ -79,11 +78,11 @@ if test "@FW_NATIVE_PACKAGE_TYPE@" != none
 erl -noshell -noinput -eval "{ ok, { myapp, [ '0.0.0' ] } } = beam_lib:version (\"src/myapp.beam\")" -s erlang halt || exit 1
 
 perl -i -pe 'm%-behaviour% && print "-vsn (flass).\n"' src/myapp.erl || exit 1
-(cd src && "${MAKE}") || exit 1
+(cd src && "@GMAKE@") || exit 1
 
 erl -noshell -noinput -eval "{ ok, { myapp, [ flass ] } } = beam_lib:version (\"src/myapp.beam\")" -s erlang halt || exit 1
 
-"${MAKE}" -s maintainer-clean
+"@GMAKE@" -s maintainer-clean
 rm -rf fw
 ( cvs -n -q up | grep '^?' ) && exit 1
 test -z "`find . -name '*.am'`" || exit 1
